### PR TITLE
fix: Add option for tag and notes

### PR DESCRIPTION
**Pull request by seanwessmith**
To allow for more extended capability, I have added `tag` and `notes` to the options

# Credit to 
- https://github.com/Coolchickenguy
- https://github.com/elgohr/Github-Release-Action/pull/54

### CODE REVIEW

**Comment by seanwessmith** [comment]
@elgohr can you please review? this mostly mirrors coolchickenguy. i also added a notes field

**Comment by elgohr** [comment]
Please reduce to tag. We'll talk about notes later.
I guess we'll have to talk about tests first.

**Comment by seanwessmith** [comment]
I've reduced to just the tag change. yea, testing would be great. something like this could work.

```yml
name: Test Github Release Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_release_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up test environment
        run: |
          echo "Setting up test environment"
          # Add any necessary setup steps here

      - name: Run Github Release action
        uses: ./ # Uses the action in the root directory of your repo
        with:
          title: "Test Release"
          tag: "v0.0.1-test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release
        run: |
          # Check if the release was created
          RELEASE_INFO=$(gh release view v0.0.1-test --json title,tagName)
          RELEASE_TITLE=$(echo $RELEASE_INFO | jq -r '.title')
          RELEASE_TAG=$(echo $RELEASE_INFO | jq -r '.tagName')
          
          if [ "$RELEASE_TITLE" != "Test Release" ]; then
            echo "Release title mismatch"
            exit 1
          fi
          
          if [ "$RELEASE_TAG" != "v0.0.1-test" ]; then
            echo "Release tag mismatch"
            exit 1
          fi
          
          echo "Release verified successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          # Delete the test release
          gh release delete v0.0.1-test --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ```

**Review by elgohr — APPROVED** [review]

**Comment by elgohr** [comment]
Thank you for the PR

**Comment by elgohr** [comment]
I would rather think of unit and integration testing.

**Pull request merged**
