### PR TITLE
Expand the documentation

### PR DESCRIPTION
**Pull request by oleg-alexandrov**
This is a proposed addition to the documentation. I don't know much what your tool does, so the last sentence is speculative. 

I am looking for the ability to create a release having source code and binaries. I don't know if your tool does that, or it just releases source code. Anyhow, hopefully  you can use some of this text to expand what is there now, which is little for the moment.

### CODE REVIEW

**Comment by elgohr** [comment]
This action creates a GitHub Release (including Tag). Not more, not less.
There’s no upload of assets, nor the attachment of source code

**Comment by oleg-alexandrov** [comment]
That's what I asked in the original issue. It is not clear, at least not to me, what this action does and what doesn't.

**Comment by oleg-alexandrov** [comment]
To add, when a user is looking at some functionality, there's no way to understand if this is the thing I need, or I need to look for something else, if the full effect of what this does is not explained. The user then has to use your functionality, and find by trial and error if it of use or not.

**Comment by elgohr** [comment]
The topic says `Publish Github releases in an action`. I guess this is pretty clear. What would you expect in one sentence?

Saying what it doesn’t would be an infinite task…

**Comment by elgohr** [comment]
`hub release create` is nearly the same in words. https://hub.github.com/hub-release.1.html

**Comment by oleg-alexandrov** [comment]
The source of confusion is that a GitHub release, to be useful at all, has to release something, like software. This action creates a link and a tag. 

It is not an infinite task to explain what parts of a GitHub release this handles and what it doesn't. 

I appreciate you responding to my question. Thank you for your time.

**Comment by elgohr** [comment]
So you suggest adding the hint, that there’s no upload of anything to the release? Sounds ok to me

**Comment by oleg-alexandrov** [comment]
That would be reasonable. I think.

**Comment by elgohr** [comment]
Like this?

**Comment by oleg-alexandrov** [comment]
Looks good. Thanks.

**Comment by wsw70** [comment]
> There’s no upload of assets, nor the attachment of source code

The source code files are added for me when the release is created (also https://github.com/elgohr/Github-Release-Action/issues/47)

**Pull request merged**
