### PR TITLE
Add option for a tag

### PR DESCRIPTION
**Pull request by Coolchickenguy**
To allow for more extended capability, I have added tags to the options.

### CODE REVIEW

**Comment by m1kesk** [comment]
any ETA on merge?

**Comment by elgohr** [comment]
Thank you for the PR.
Could you please squash the history into one commit?

**Comment by seanwessmith** [comment]
please rush this one along! :D

**Comment by elgohr** [comment]
https://github.com/elgohr/Github-Release-Action/pull/56

**Pull request closed without merging**
